# Run the project's linting suite via Pre-Commit
name: Lint

on:  # yamllint disable-line rule:truthy
  push:
    branches:
    - master
    - main
    - '*.*'
    - 'staging*'
  pull_request:
    branches:
    - master
    - main
    - '*.*'
    - 'staging*'

jobs:
  lint:
    name: Lint with Pre-Commit

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    - name: Run pre-commit hooks
      uses: tox-dev/action-pre-commit-uv@v1
